@URL=http://localhost:8080

### Autores

//paginacion y ordenamiento
GET {{URL}}/autores?page=0&size=5 HTTP/1.1
###
GET {{URL}}/autores?page=0&size=5&sortBy=idAutor  HTTP/1.1

###

GET {{URL}}/autores HTTP/1.1

###
POST {{URL}}/autores HTTP/1.1
content-type: application/json

{
  "nombre1": "Homero II"
}

###
PUT {{URL}}/autores/26 HTTP/1.1
content-type: application/json

{
  "nombre": "Aristrocates"
}

###
PATCH {{URL}}/autores/26



//paginacion y ordenamiento
###
GET {{URL}}/categorias?page=0&size=10 HTTP/1.1
###
GET {{URL}}/categorias?page=0&size=5&sortBy=nombre  HTTP/1.1

### Categorias
GET {{URL}}/categorias HTTP/1.1

###
POST {{URL}}/categorias HTTP/1.1
content-type: application/json

{
  "nombre": "Literatura Clasica"
}

###
PUT {{URL}}/categorias/11 HTTP/1.1
content-type: application/json

{
  "nombre": "Biografia"
}

###
PATCH {{URL}}/categorias/11

### Idiomas

//paginacion y ordenamiento
###
GET {{URL}}/idiomas?page=0&size=5 HTTP/1.1
###
GET {{URL}}/idiomas?page=0&size=5&sortBy=nombre HTTP/1.1

###

GET {{URL}}/idiomas?sortBy=idIdioma

###
POST {{URL}}/idiomas HTTP/1.1
content-type: application/json

{
  "nombre": "Aleman"
}

###
PUT {{URL}}/idiomas/3 HTTP/1.1
content-type: application/json

{
  "nombre": "Portugues"
}

###
PATCH {{URL}}/idiomas/3

### Subgeneros

//paginacion y ordenamiento
###
GET {{URL}}/subgeneros?page=0&size=5 HTTP/1.1
###
GET {{URL}}/subgeneros?page=0&size=5&sortBy=idSubgenero&sortBy=nombre  HTTP/1.1


GET {{URL}}/subgeneros HTTP/1.1

###
POST {{URL}}/subgeneros HTTP/1.1
content-type: application/json

{
  "nombre": "prueba"
}

###
PUT {{URL}}/subgeneros/12 HTTP/1.1
content-type: application/json

{
  "nombre": "prueba xd"
}

###
PATCH {{URL}}/subgeneros/12

### Editoriales

//paginacion y ordenamiento
###
GET {{URL}}/editoriales?page=0&size=5 HTTP/1.1
###
GET {{URL}}/editoriales?page=0&size=5&sortBy=nombre  HTTP/1.1

GET {{URL}}/editoriales HTTP/1.1

###
POST {{URL}}/editoriales HTTP/1.1
content-type: application/json

{
  "nombre": "Siglo XXI"
}

###
PUT {{URL}}/editoriales/11 HTTP/1.1
content-type: application/json

{
  "nombre": "Siglo XXI"
}

###
PATCH {{URL}}/editoriales/11

### Libros
GET {{URL}}/libros?page=0&size=5 HTTP/1.1
###
GET {{URL}}/libros
###
GET {{URL}}/libros?page=0&size=5&sortBy=kojlh



###
GET {{URL}}/libros/3 HTTP/1.1

###
POST {{URL}}/libros
content-type: application/json

{
  "serialNumber": "CN004",
  "idAutor": 1,
  "idEditorial": 1,
  "idSubgenero": 1,
  "idCategoria": 1
}

###
PUT {{URL}}/libros/28 HTTP/1.1
content-type: application/json

{
  "serialNumber": "CN004",
  "nombre": "Cien años de pereza",
  "autor": {
    "idAutor": 3
  },
  "idioma": {
    "idIdioma": 1
  },
  "editorial": {
    "idEditorial": 2
  },
  "categoria": {
    "idCategoria": 2
  },
  "subGenero": {
    "idSubgenero": 2
  },
  "anio": 1967,
  "unidades": 100,
  "cantidadPaginas": 471,
  "urlImagen": "https://example.com/cien-anos-de-soledad.jpg"
}

###
PATCH {{URL}}/libros/28
###
GET {{URL}}/libros/3


###
GET {{URL}}/clientes HTTP/1.1

###
GET {{URL}}/clientes?page=0&size=5&sortBy=idCliente HTTP/1.1

###
POST {{URL}}/clientes HTTP/1.1
content-type: application/json

{
  "dni": "71558974",
  "nombre": "Nelson",   
  "apellido": "Arango",  
  "telefono": "965812458",
  "correo": "NelsonArango@gmail.com",
  "direccion": "av.Arquipa",
  "fecha": "2000-01-20"  
}

###
PUT {{URL}}/clientes/5 HTTP/1.1
content-type: application/json

{
  "dni": "20214545",
  "nombre": "Juan Carlos",   
  "apellido": "Garcia",  
  "telefono": "965874458",
  "correo": "JuanGarcia14@gmail.com",
  "direccion": "av.los Heroes",
  "fecha": "1999-01-12"  
}
###
PATCH {{URL}}/clientes/8

###
GET {{URL}}/prestamos HTTP/1.1

###
GET {{URL}}/prestamos?page=0&size=5&sortBy=idprestamo HTTP/1.1

###

POST {{URL}}/prestamos HTTP/1.1
content-type: application/json

{
  "cliente": {
    "idCliente": 4
  },
  "cantidad": 5,
  "fechaPrestamo": "2024-10-12",
  "fechaDevolucion": "2024-10-20"

}

###
PUT {{URL}}/prestamos/4 HTTP/1.1
content-type: application/json

{
  "cliente": {
    "idCliente": 4
  },
  "cantidad": 5,
  "fechaPrestamo": "2024-10-13",
  "fechaDevolucion": "2024-10-25"

}
